### ISSUE TITLE
Error when running the last step wann2j

### ISSUE THREAD

**Issue by ChenqiangHua** [mailhexu/TB2J#28]
Reading atomic structure from file ./POSCAR.
Reading Wannier90 hamiltonian: spin up.
Reading Wannier90 hamiltonian: spin down.
Starting to calculate exchange.

Traceback (most recent call last):
  File "/beegfs/home/b00004/anaconda3/bin/wann2J.py", line 186, in <module>
    run_wann2J()
  File "/beegfs/home/b00004/anaconda3/bin/wann2J.py", line 156, in run_wann2J
    gen_exchange(path=args.path,
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/manager.py", line 98, in gen_exchange
    exchange = ExchangeCL2(tbmodels=(tbmodel_up, tbmodel_dn),
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/exchange.py", line 72, in __init__
    self.set_tbmodels(tbmodels)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/exchangeCL2.py", line 30, in set_tbmodels
    self.Gup = TBGreen(self.tbmodel_up,
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/green.py", line 92, in __init__
    self._prepare_eigen()
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/green.py", line 156, in _prepare_eigen
    self.evals, self.evecs = self._reduce_eigens(self.evals,
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/TB2J/green.py", line 98, in _reduce_eigens
    istart, iend = ts[0], ts[-1] + 1
IndexError: index 0 is out of bounds for axis 0 with size 0

I use similar structure, i have succussfully got the results.  but at this time  sth wrong

**Comment by ChenqiangHua** [comment]
pleause help me.  or tell me somewhere maybe wrong?    the wannierise process is succussful

the command  I used is like this: 
wann2J.py --efermi -0.2822 --kmesh  5 5 1 --elements Fe --prefix_up wannier90.up --prefix_down wannier90.dn  --emin -10.0 --emax 0.0          


Thanks!

**Comment by mailhexu** [comment]
Hi, 
The error message shows that TB2J doesn't find any band in the energy range speicified by the efermi, emin and emax. Maybe these options are not correctly given, or the Wannier Hamitonian is wrong. Could you check the Wannier90 band structure, and the fermi energy. 
Best wishes,
HeXu

**Comment by ChenqiangHua** [comment]
Much thanks!  let me try ,maybe sth wrong in my wannier calculation or projection!   

thanks again!
