### ISSUE TITLE
error in using ABACUS

### ISSUE THREAD

**Issue by summitmoon** [mailhexu/TB2J#63]
Dear all,

I am using TB2J interface wth ABACUS software, however, I met a issue as:

TB2J version 0.9.0.1
Copyright (C) 2018-2024  TB2J group.
This software is distributed with the 2-Clause BSD License, without any warranty. For more details, see the LICENSE file delivered with this software.
Traceback (most recent call last):
  File "abacus2J.py", line 151, in <module>
    run_abacus2J()
  File "abacus2J.py", line 132, in run_abacus2J
    gen_exchange_abacus(
  File ".local/lib/python3.11/site-packages/TB2J/abacus/gen_exchange_abacus.py", line 38, in gen_exchange_abacus
    parser = AbacusParser(outpath=outpath, spin=None, binary=binary)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".local/lib/python3.11/site-packages/TB2J/abacus/abacus_wrapper.py", line 125, in __init__
    self.read_atoms()
  File ".local/lib/python3.11/site-packages/TB2J/abacus/abacus_wrapper.py", line 147, in read_atoms
    self.atoms = read_abacus(path1)
                 ^^^^^^^^^^^^^^^^^^
  File ".local/lib/python3.11/site-packages/ase/utils/__init__.py", line 577, in iofunc
    obj = func(fd, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".local/lib/python3.11/site-packages/TB2J/abacus/stru_api.py", line 810, in read_abacus
    atom_block = np.array(atom_block)
                 ^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (96,) + inhomogeneous part.

I am not sure what is the exact error in this calculation. Could you help me to figure out them?

Thank you.

**Comment by summitmoon** [comment]
Sorry. I have figured out this question. The issue because of the structure file is not exact the same as the standard STRU
