### ISSUE TITLE
TB2J-abacus question 

### ISSUE THREAD

**Issue by matphy1** [mailhexu/TB2J#65]
I used abacus 3.8.3 to calculate the non-collinear system, and after using lcao-based group calculation, I encountered such an error when running TB2J. The system has 12 magnetic atoms and the magnetic moments are non-collinear. What is the reason? Can you help me analyze it? thank you

This is the log file:

TB2J version 0.9.0.1
Copyright (C) 2018-2024 TB2J group.
This software is distributed with the 2-Clause BSD License, without any warranty. For more details, see the LICENSE file delivered with this software.

Traceback (most recent call last):
File "/home/mat/apps/anaconda3/bin/abacus2J.py", line 151, in
run_abacus2J()
File "/home/mat/apps/anaconda3/bin/abacus2J.py", line 132, in run_abacus2J
gen_exchange_abacus(
File "/home/mat/apps/anaconda3/lib/python3.11/site-packages/TB2J/abacus/gen_exchange_abacus.py", line 38, in gen_exchange_abacus
parser = AbacusParser(outpath=outpath, spin=None, binary=binary)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/mat/apps/anaconda3/lib/python3.11/site-packages/TB2J/abacus/abacus_wrapper.py", line 125, in init
self.read_atoms()
File "/home/mat/apps/anaconda3/lib/python3.11/site-packages/TB2J/abacus/abacus_wrapper.py", line 147, in read_atoms
self.atoms = read_abacus(path1)
^^^^^^^^^^^^^^^^^^
File "/home/mat/apps/anaconda3/lib/python3.11/site-packages/ase/utils/init.py", line 577, in iofunc
obj = func(fd, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/mat/apps/anaconda3/lib/python3.11/site-packages/TB2J/abacus/stru_api.py", line 810, in read_abacus
atom_block = np.array(atom_block)
^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (21,) + inhomogeneous part.

**Comment by mailhexu** [comment]
Hi, Could you try with the latest version of TB2J? non-collinear spin was not supported in version 0.9.0.1. 
Best, 
HeXu
