### ISSUE TITLE
ABACUS version 3.8.3 not able to read fermi energy

### ISSUE THREAD

**Issue by kluophysics** [mailhexu/TB2J#66]
Hello,

I have tried to run ABACUS example your provided. I have tried many versions. The one reported here is with 3.8.3 (from other issue which seems to have no issue reported here). However, it seems the EFERMI is missing in the running_scf.log file. Can you take a look? 
Thanks and 谢谢！

Below is the error message.
```
$ ./getJ.sh 
/home/kluo/.conda/envs/python3/bin/abacus2J.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('TB2J==0.9.0.3', 'abacus2J.py')

TB2J version 0.9.0.1
Copyright (C) 2018-2024  TB2J group.
This software is distributed with the 2-Clause BSD License, without any warranty. For more details, see the LICENSE file delivered with this software.


Traceback (most recent call last):
  File "/home/kluo/.conda/envs/python3/bin/abacus2J.py", line 4, in <module>
    __import__('pkg_resources').run_script('TB2J==0.9.0.3', 'abacus2J.py')
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 755, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1744, in run_script
    exec(script_code, namespace, namespace)
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/TB2J-0.9.0.3-py3.11.egg/EGG-INFO/scripts/abacus2J.py", line 151, in <module>
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/TB2J-0.9.0.3-py3.11.egg/EGG-INFO/scripts/abacus2J.py", line 132, in run_abacus2J
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/TB2J-0.9.0.3-py3.11.egg/TB2J/abacus/gen_exchange_abacus.py", line 38, in gen_exchange_abacus
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/TB2J-0.9.0.3-py3.11.egg/TB2J/abacus/abacus_wrapper.py", line 126, in __init__
  File "/home/kluo/.conda/envs/python3/lib/python3.11/site-packages/TB2J-0.9.0.3-py3.11.egg/TB2J/abacus/abacus_wrapper.py", line 214, in read_efermi
ValueError: EFERMI not found in the DFT/OUT.Fe/running_scf.log  file.

```

**Comment by mailhexu** [comment]
Thanks for reporting. Could you send the ABUCUS output and log files so that I can try to see if the fermi energy can be found there?
Best regards, 
HeXu

**Comment by kluophysics** [comment]
> Thanks for reporting. Could you send the ABUCUS output and log files so that I can try to see if the fermi energy can be found there? Best regards, HeXu

Sorry, I doubled check the output and found EFERMI is there. It turns out that I used root to run and executed getJ.sh using ordinary user. I will close it.
